### ISSUE TITLE
Issue with Azure Blob Storage Provider

### ISSUE THREAD

**Issue by wroughtec** [mrflo/Umbraco-MediaEditor#1]
When processing the que I am getting a 500 error I believe caused by the fact our media items are on an Azure Blob using:
https://our.umbraco.org/projects/backoffice-extensions/azure-blob-storage-provider/

onErrorItem
{Message: "An error has occurred.", ExceptionMessage: "'https:/url.blob.core.windows.net/img/384353' is not a valid virtual path.", ExceptionType: "System.Web.HttpException", StackTrace: "   at System.Web.Util.UrlPath.CheckValidVirtualPat…ers.MediaEditorController.<Upload>d__c.MoveNext()"

I assume it's because its a full url rather than a virtual path, is this something that could be resolved?

**Comment by mrflo** [comment]
Hello wroughtec,

It's not working with Azure because it's using local storage methods to upload files.
But it wouldn't be that complicated to change those methods by a Windows Azure one from the plugin: https://github.com/idseefeld/UmbracoAzureBlobStorage/blob/master/AzureBlobFileSystem.cs

I am not using this blob storage for the moment but that could be a nice update to this extension.
